In [1]:
import pandas as pd
import numpy as np
import os
from matplotlib import pyplot as plt
import numpy as np
import math
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA 

votes_file = '../assets/datasets/votes.csv'
airport_file = '../assets/datasets/Airport_operations.csv'

# Case #1: Congressional Voting Data

After you've downloaded the data from the repository, go ahead and load it with Pandas

In [2]:
vote = pd.read_csv(votes_file)
ap = pd.read_csv(airport_file)

In [3]:
vote.head()

Unnamed: 0       Class   V1 V2 V3   V4   V5 V6 V7 V8 V9 V10  V11  V12 V13  \
0           1  republican    n  y  n    y    y  y  n  n  n   y  NaN    y   y   
1           2  republican    n  y  n    y    y  y  n  n  n   n    n    y   y   
2           3    democrat  NaN  y  y  NaN    y  y  n  n  n   n    y    n   y   
3           4    democrat    n  y  y    n  NaN  y  n  n  n   n    y    n   y   
4           5    democrat    y  y  y    n    y  y  n  n  n   n    y  NaN   y   

  V14 V15  V16  
0   y   n    y  
1   y   n  NaN  
2   y   n    n  
3   n   n    y  
4   y   y    y

In [4]:
len(vote)

435

In [5]:
vote = vote.dropna()
len(vote)

232

In [6]:
vote.head()

Unnamed: 0       Class V1 V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13 V14 V15  \
5            6    democrat  n  y  y  n  y  y  n  n  n   n   n   n   y   y   y   
8            9  republican  n  y  n  y  y  y  n  n  n   n   n   y   y   y   n   
19          20    democrat  y  y  y  n  n  n  y  y  y   n   y   n   n   n   y   
23          24    democrat  y  y  y  n  n  n  y  y  y   n   n   n   n   n   y   
25          26    democrat  y  n  y  n  n  n  y  y  y   y   n   n   n   n   y   

   V16  
5    y  
8    y  
19   y  
23   y  
25   y

Next, let's define the x and y variables: 

In [8]:
X = vote.iloc[:, 2:]
X.head()

V1 V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13 V14 V15 V16
5   n  y  y  n  y  y  n  n  n   n   n   n   y   y   y   y
8   n  y  n  y  y  y  n  n  n   n   n   y   y   y   n   y
19  y  y  y  n  n  n  y  y  y   n   y   n   n   n   y   y
23  y  y  y  n  n  n  y  y  y   n   n   n   n   n   y   y
25  y  n  y  n  n  n  y  y  y   y   n   n   n   n   y   y

In [9]:
y = vote['Class']

Next, create the covariance matrix from the standardized x-values and decompose these values to find the eigenvalues and eigenvectors

In [11]:
X = X.applymap(lambda x: 1 if x == 'y' else 0)

In [14]:
X_s = StandardScaler().fit_transform(X)
X_s = pd.DataFrame(X_s, columns= X.columns)

In [24]:
X_s_corr = np.cov(X_s.values.T)

Now, let's check the eigenvalues: 

In [25]:
eig_val, eig_vec = np.linalg.eig(X_s_corr)
print eig_val


[ 7.72441821  1.38414615  1.0518882   0.9697194   0.80765992  0.72917396
  0.10499427  0.17814579  0.20187395  0.27597898  0.32292795  0.35727403
  0.37876783  0.49242232  0.54322922  0.54664388]


And the eigenvectors: 

In [26]:
print eig_vec

[[  1.84608588e-01   1.79544628e-01   3.96877507e-02  -5.18236597e-01
   -4.58868451e-01   4.65381884e-01   1.79916607e-02  -8.13810996e-02
   -5.44744281e-03  -1.59364099e-01   1.69450750e-01   8.32207705e-02
   -6.61375184e-02  -2.92779341e-01   2.76730743e-01   4.13800644e-02]
 [ -4.74282209e-02   6.48573848e-01  -1.18761132e-01  -3.73350711e-01
    9.30132071e-02  -4.61402638e-01  -1.75377517e-02  -6.80041937e-02
    1.26056140e-01  -4.14475796e-02  -5.17595157e-04  -1.22653581e-01
    2.05367759e-01   6.86284905e-02   2.86201962e-02  -3.41722769e-01]
 [  2.86321599e-01   4.73091554e-02  -1.88931793e-01  -8.32651252e-02
    1.59714378e-01  -5.04457911e-02   1.35255869e-01  -1.33880242e-01
    9.43254701e-02  -2.12382774e-01  -7.55148372e-01   9.54559997e-02
    6.08936441e-02  -1.21667214e-01   9.24259191e-02   3.85310015e-01]
 [ -3.04936211e-01  -1.42532176e-01   4.73997626e-02  -1.28224416e-01
   -1.50912081e-02   2.83604055e-02   3.15904889e-01   5.49808623e-02
   -6.28745988e-0

To find the principal componants, find the eigenpairs, and sort them from highest to lowest. 

In [27]:
eig_pairs = []

for i in range(len(eig_val)):
    eig_pairs.append([eig_val[i], eig_vec[i]])
    
eig_pairs.sort(key = lambda x: x[0], reverse=True)
eig_pairs

[[7.7244182114100282,
  array([ 0.18460859,  0.17954463,  0.03968775, -0.5182366 , -0.45886845,
          0.46538188,  0.01799166, -0.0813811 , -0.00544744, -0.1593641 ,
          0.16945075,  0.08322077, -0.06613752, -0.29277934,  0.27673074,
          0.04138006])],
 [1.3841461523614766,
  array([ -4.74282209e-02,   6.48573848e-01,  -1.18761132e-01,
          -3.73350711e-01,   9.30132071e-02,  -4.61402638e-01,
          -1.75377517e-02,  -6.80041937e-02,   1.26056140e-01,
          -4.14475796e-02,  -5.17595157e-04,  -1.22653581e-01,
           2.05367759e-01,   6.86284905e-02,   2.86201962e-02,
          -3.41722769e-01])],
 [1.0518881973423055,
  array([ 0.2863216 ,  0.04730916, -0.18893179, -0.08326513,  0.15971438,
         -0.05044579,  0.13525587, -0.13388024,  0.09432547, -0.21238277,
         -0.75514837,  0.095456  ,  0.06089364, -0.12166721,  0.09242592,
          0.38531001])],
 [0.96971939993210199,
  array([-0.30493621, -0.14253218,  0.04739976, -0.12822442, -0.01509121

Now, calculate the explained variance. Recall the methods we learned in lesson 2.2!

In [28]:
sum_val = sum(eig_val)

var_exp = [(x / sum_val) * 100 for x in eig_val]
var_exp

[48.06952065828979,
 8.6136250322063894,
 6.5459637280730769,
 6.0346223433274684,
 5.0261164178178381,
 4.5376935556808471,
 0.65338568150134479,
 1.1086120305738507,
 1.2562737953055516,
 1.7174338427323597,
 2.0096001083200719,
 2.2233378520306086,
 2.357095072160226,
 3.0643738305371042,
 3.3805481914049662,
 3.4017978600385219]

Now, calculate the explained variance and the Cumulative explained variance

In [29]:
cum_var_exp = np.cumsum(var_exp)
cum_var_exp

array([  48.06952066,   56.68314569,   63.22910942,   69.26373176,
         74.28984818,   78.82754174,   79.48092742,   80.58953945,
         81.84581324,   83.56324709,   85.57284719,   87.79618505,
         90.15328012,   93.21765395,   96.59820214,  100.        ])

Now, conduct a PCA using scikit learn

http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

# Case #2: Airport Delays

First, let's define the x and y variables: Airport is going to be our target variable

Then, standardize the x variable for analysis

Next, create the covariance matrix from the standardized x-values and decompose these values to find the eigenvalues and eigenvectors

Then, check your eigenvalues and eigenvectors:

To find the principal components, find the eigenpairs, and sort them from highest to lowest. 

Next, Calculate the explained variance

Finally, conduct the PCA - use the results above to guide your selection of n components

**Bonus**: build and contrast classification models to predict the target classes for each problem, using both the original (or n-best) features and the principal components. If you arrive at <= 3-dimensional feature space, try plotting your data!