In [1]:
import numpy as np
# create array x

arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])

In [2]:
# print the shape of x
arr.shape

(12,)

In [3]:
# create a two dimensional array

arr_2 = np.array([[0,1,2,3,4,5], [6,7,8,9,10,11]])

In [4]:
# print shape of 2d array
arr_2.shape

(2, 6)

In [5]:
# reshape the array to 2 x 6
arr_2.reshape([6,2])

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
# reshape the array to 1 x 12
arr_2.reshape([1,12])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [15]:
type(arr_2)

NameError: name 'dtype' is not defined

In [7]:
# transpose the array
arr_2.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [9]:
# indexing method 1
arr_2[1,4]

10

In [10]:
# indexing method 2
arr_2[1][4]

10

In [11]:
# indexing method 3
y = np.arange(35).reshape(5,7)
print y

y[1:5:2,::3]


[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 7, 10, 13],
       [21, 24, 27]])

In [13]:
# indexing method 4
x = np.arange(10,1,-1)
print x

x[np.array([3, 3, 1, 8])]

[10  9  8  7  6  5  4  3  2]


array([7, 7, 9, 2])

In [11]:
# indexing method 5

In [10]:
# indexing method 6